### ISSUE TITLE
how to to combine text and icons with the recorded video ?

### ISSUE THREAD

**Issue by trollblocks** [lincf0912/LFMediaEditingController#10]
hello how to get the video edited with pictures and texts when i press apply 

i got only a video without text and pictures 

or where can i get the list of stickers or texts   so i can do it myself 

thank you .

**Comment by lincf0912** [comment]
You can't get a list, but you can set up a list of stickers.
LFVideoEditingController.h
@property (nonatomic, strong) NSString *stickerPath;

You'll get LFVideoEdit object when you press apply.
@property (nonatomic, readonly) NSURL *editFinalURL; // This is the edited video url.
@property (nonatomic, readonly) UIImage *editPreviewImage; // This is the first frame of the video.

**Comment by trollblocks** [comment]
thank for your answer the video from editFinalUrl is just like the original without stickers apply on it 
editPreviewImage also containing a screen without stickers on it .

maybe their is a bug on the system that do not provide stickers to the video or the first frame. 

the exemple project from the github page also did not provide stickers  on editPreviewImage  
or editFinalURL

**Comment by lincf0912** [comment]
oops. I'm sorry. This is a issue, and I'll fix it soon.

**Comment by lincf0912** [comment]
Please update the version to [1.2.2](https://github.com/lincf0912/LFMediaEditingController/releases/tag/1.2.2)

**Comment by trollblocks** [comment]
amazing it work great now  problem solved !.  thank you !!!
