### ISSUE TITLE
关于滤镜功能

### ISSUE THREAD

**Issue by frankxzx** [lincf0912/LFMediaEditingController#12]
首先感谢贡献这么棒的组件！
将来是否考虑添加视频滤镜的功能？

---
最近我在 LFMediaEditingController 上做二次开发，相关滤镜的功能参考了另一个开源项目 SCRecorder，

由于对 AVFoudation, CoreImage 框架不够熟悉，在修改 LFVideoExportSession: exportAsynchronouslyWithCompletionHandler 导出视频的逻辑时，
我这边就简单粗暴的加入 AVMutableVideoComposition: videoCompositionWithAsset: applyingCIFiltersWithHandler: 

系统抛出异常
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[AVCoreImageFilterCustomVideoCompositor startVideoCompositionRequest:] Expecting video composition to contain only AVCoreImageFilterVideoCompositionInstruction'
*** 

请问是否有什么好的建议对于滤镜视频导出的逻辑添加？非常感谢🙏

**Comment by frankxzx** [comment]
Asset 入参填错，正确代码如下
```
   #import "SCFilter+VideoComposition.h"

    UIImageOrientation orientation = [self orientationFromAVAssetTrack:assetVideoTrack];
    
    if (orientation != UIImageOrientationUp || self.overlayView) {
        SCFilter *filter = [SCFilter filterWithCIFilterName:@"CIGaussianBlur"];
        self.videoComposition = [filter videoCompositionWithAsset:self.composition];
//        self.videoComposition = [AVMutableVideoComposition videoComposition];
        self.videoComposition.frameDuration = CMTimeMake(1, 30); // 30 fps
    }
```

**Comment by lincf0912** [comment]
暂时没有这方面的考虑。
如果要加入滤镜的功能，会新开一个项目来处理的。
扩展滤镜方面可以使用GPUImage更加简单

**Comment by frankxzx** [comment]
GPUImage 感觉不够轻量级，SCRecorder 中的 SCFilter 足够实现简单滤镜，而且考虑到 iOS 12 好像摒弃 OpenGL 的支持了。

**Comment by frankxzx** [comment]
好像同时调用裁剪和滤镜会有问题 [stackoverflow](https://stackoverflow.com/questions/45090477/setting-avmutablevideocomposition-instruction-causes-handler-not-to-be-called)

**Comment by lincf0912** [comment]
尝试下执行2次AVAssetExportSession，先将它剪辑了，再添加滤镜。

**Comment by lincf0912** [comment]
[版本1.2.7](https://github.com/lincf0912/LFMediaEditingController/releases/tag/1.2.7) 已经支持视频滤镜了。
[滤镜框架](https://github.com/lincf0912/LFMediaEditingController/tree/master/LFMediaEditingController/class/vendors/LFFilterSuite)
