### ISSUE TITLE
请问在涂鸦的时候能否实现双指缩放？

### ISSUE THREAD

**Issue by netsesame2** [lincf0912/LFMediaEditingController#13]
非常棒的库，源码也写的很清晰，减少了我很多工作量。

因为需要涂鸦的时候能双指缩放，模拟器上试了但看不出来，在此请教是否已实现。如果没有，该如何修改源码实现，请不吝指教。

**Comment by lincf0912** [comment]
模拟器使用双指：按住option键

**Comment by lincf0912** [comment]
可以横屏编辑的，只是编辑时不能随意切换横竖屏。
原设计模式的横屏编辑控件位置与竖屏是2套不一样的布局。但是其中涉及到比较多的位置计算与时间的消耗。也有主要的一部分是最初设计的时候并没考虑到横屏的。有一些朋友是iPad的APP也会使用。才萌发横屏的考虑。

**Comment by netsesame2** [comment]
我在安卓端也是这样实现的横竖屏，用布局文件实现了两套不同的布局。但到了ios这边，看了你的库代码，布局全部使用代码实现的，而没有采用xib之类的辅助，再加上对xcode的布局不太熟悉，因此觉得自己改动工作量会很大。

但我的需求，也是不允许用户在编辑的时候随意切换的。只是在竖屏和横屏下，都采用了一样的布局，要求用户把手机横着用。确实比较繁琐

**Comment by netsesame2** [comment]
@lincf0912 涂鸦时的双指缩放，发现有时能缩放，有时不能缩放。跟踪发现双指触摸的消息经常不能捕捉到，导致双指缩放被上层的ScrollView识别为单指。

困扰了好久了，请问该如何解决？

**Comment by lincf0912** [comment]
应该是手势优先级的问题。我有空解决下。

发自我的 iPhone

**Comment by netsesame2** [comment]
@lincf0912 是的，双指触摸经常会有两指触摸的时间差。导致在ScrollView在首次识别到单指消息后，就误传到底层DrawView层去绘画。随后识别到双指，DrawView停止了绘画，但又不返回控制权。出现的现象就是：双指不能缩放，在屏幕上出现画的很短的一条线，然后停止响应。

这个问题是客户发现的，但是因为涉及到消息的传递，我自己很难修复。麻烦你解决了。

**Comment by lincf0912** [comment]
还在上传。你迟点再更新试试。😀

**Comment by netsesame2** [comment]
ok。解决了燃眉之急！
