### ISSUE TITLE
屏幕自动旋转后，图片显示不能居中

### ISSUE THREAD

**Issue by netsesame2** [lincf0912/LFMediaEditingController#14]
如果开启屏幕自动旋转，编辑器中居中的图片在旋转后，变成了居于左上角位置，且缩放、旋转等操作均不能正常工作。

请教该如何处理？

**Comment by lincf0912** [comment]
因数据可以多次重复编辑，暂时未能处理横竖屏切换。

**Comment by netsesame2** [comment]
是这样，我的相机是横屏的，拍完照后调用的编辑器，存在了一个从横屏（相机）到竖屏（编辑）的转换，这时候发现屏幕旋转后，图片在编辑界面中的显示变成了左上角，而且不能调整。

**Comment by lincf0912** [comment]
麻烦你看一下demo的实现。虽然它不是相机，但我认为是一样的。
你可以横屏启动demo，然后编辑。

**Comment by netsesame2** [comment]
好，我再看下
