### ISSUE TITLE
挺好的库！一点点反馈~

### ISSUE THREAD

**Issue by whatsbug** [lincf0912/LFMediaEditingController#15]
- 能否默认就进入某个模式，比如默认就涂鸦模式、默认就裁剪模式，现在默认没有进入任何模式。

- 当裁剪的图片背景色是大面积白色的时候，移动图片时，裁剪区域的辅助线很难看清楚，因为现在移动时，那层灰色的蒙版会消失。

- 画笔粗细无法调整：在裁剪完长图的十分之一再涂鸦时，画笔会变得非常粗，如果此时添加文字，文字也非常大。

**Comment by lincf0912** [comment]
感谢你的反馈。
下个版本会针对长图作出比较大的调整。

发自我的 iPhone

**Comment by netsesame2** [comment]
@whatsbug 你说的几个问题我都遇到，我是自己解决的：
1. 在加载图片后，延迟500ms打开裁剪功能；
2. 裁剪辅助线改成绿色边框；
3. 增加画笔粗细调整拉杆

**Comment by whatsbug** [comment]
@netsesame2 哈哈，我的解决方案也差不多，稍微有点不同的是，第1点我是先模拟点击涂鸦按钮，然后延迟片刻再模拟点击裁剪按钮，这样做的好处是在退出裁剪模式时就可以直接涂鸦了。第2点我是在裁剪模式下那个LFGridView的layer里面加了一个透明度为0.2的黑色layer。这样不管图片背景是什么颜色都能看得清辅助线了。。。但是还是期待由作者来改，这样就能愉快的使用CocoaPods了。。

**Comment by netsesame2** [comment]
需求有差异，其他地方我也改动了很多。作者的库结构庞大，气势恢宏，每一次升级，我都要小心翼翼的逐个文件对照

**Comment by lincf0912** [comment]
版本[1.2.5](https://github.com/lincf0912/LFMediaEditingController/releases/tag/1.2.5) 已经对画笔进行了调整。
长图的适配也即将接近尾声了，但会等到适配iPhoneX后才归纳到一个新版本。然后再排默认模式的开发吧。

**Comment by whatsbug** [comment]
@lincf0912 👍👍👍，老哥我刚才发现在demo里使用马赛克啊或滤镜功能后内存增加明显，此时点击右上角的完成按钮，再退到demo首页，部分内存并没有释放，重复这个流程，内存也一直在增加。

**Comment by whatsbug** [comment]
哦补充一点是用模拟器测试的，内存变化使用Xcode看的

**Comment by lincf0912** [comment]
好的。感谢你的反馈。我跟进下。

**Comment by lincf0912** [comment]
@whatsbug @netsesame2 
[版本1.2.6](https://github.com/lincf0912/LFMediaEditingController/releases/tag/1.2.6)
希望对你们的项目有所帮助。

**Comment by whatsbug** [comment]
haode👍🤠🤡
