### ISSUE TITLE
didFinishPhotoEdit 回调如何获取被编辑图片的原文件的文件名

### ISSUE THREAD

**Issue by fairytale110** [lincf0912/LFMediaEditingController#16]
- (void)lf_PhotoEditingController:(LFPhotoEditingController *)photoEditingVC didFinishPhotoEdit:(LFPhotoEdit *)photoEdit;

photoEdit 如何拿到编辑前图片文件名称和类型呢？请教

**Comment by lincf0912** [comment]
不能拿到的。因为传递给框架的参数只有UIImage的对象。你应该在初始化这个UIImage的时候拿到这些信息。
