### ISSUE TITLE
想问一下，视频超过10秒之后，获取的视频类型是MOV，为啥不是MP4呢，这个要怎么修改呢？

### ISSUE THREAD

**Issue by Miss-Leely** [lincf0912/LFMediaEditingController#17]
类似微信朋友圈，超过说10秒之后，先做视频裁剪，获取的编辑对象为空。

**Comment by lincf0912** [comment]
我不是很明白。意思是你编辑一个超过10s的视频，编辑后代理返回的LFVideoEdit对象是nil?
1、如果有编辑过的话，LFVideoEdit不可能是nil的。
2、如果没有编辑过/编辑后又重置了，LFVideoEdit是nil的。这时获取的值应该是之前的入参AVAsset

**Comment by Miss-Leely** [comment]
可能是我没有描述清楚，是这样的，超过10之后，就像微信那样有个提示语，还有个编辑按钮，点击编辑按钮，到视频编辑页面，这时候获取的LFVideoEdit为nil。UI界面显示如下，代码如下：
 LFVideoEditingController *videoEditingVC = [[LFVideoEditingController alloc] init];
            editingVC = videoEditingVC;
            videoEditingVC.isShow = YES;//isShow 是我添加的一个判断条件
            videoEditingVC.minClippingDuration = 3.f;
            videoEditingVC.operationType = LFVideoEditOperationType_All;
            LFVideoEdit *videoEdit = [[LFVideoEditManager manager] videoEditForAsset:model];
            if (videoEdit) {
                videoEditingVC.videoEdit = videoEdit;
            } else {
                LFPhotoPreviewVideoCell *cell = [_collectionView visibleCells].firstObject;
                /** 当前显示的图片 */
                [videoEditingVC setVideoAsset:cell.asset placeholderImage:cell.previewImage];
            }
            videoEditingVC.delegate = self;
            if (imagePickerVc.videoEditLabrary) {
                imagePickerVc.videoEditLabrary(videoEditingVC);
            }
![image](https://user-images.githubusercontent.com/17715329/51824303-dddfd100-231c-11e9-84c6-a695c7723d4d.png)

**Comment by lincf0912** [comment]
我想你所使用的LFMediaEditingController代码并不是最新的。你可以先使用demo来测试它。然后再决定更新代码。
顺便一提。就朋友圈这个功能，你可以到[LFImagePickerController](https://github.com/lincf0912/LFImagePickerController)下载demo来看看。但目前LFMediaEditingController的灵活性有限，并不能直接显示编辑的剪切模式。LFMediaEditingController的兼容性与灵活性正在调整阶段。继续关注更新。

**Comment by lincf0912** [comment]
LFMediaEditingController的剪辑界面是有时间显示的。我看你的截图是没有的。所以才断定代码并非最新。或者你先下载demo来看看。即使你调整到直接显示剪辑界面，如果没有发生剪辑，LFVideoEdit一样会是nil的。

**Comment by Miss-Leely** [comment]
呃。。。我把时间显示的代码注销了。我昨天排查了一下，就是LFVideoEdit videoEdit = [[LFVideoEditManager manager] videoEditForAsset:model];这句代码，model有值，获取的数据为空。没有搞懂，不知道怎么修改。

**Comment by lincf0912** [comment]
代理方法- (void)lf_VideoEditingController:(LFVideoEditingController *)videoEditingVC didFinishPhotoEdit:(LFVideoEdit *)videoEdit回调的videoEdit是nil吧。就是说并没有发生编辑。但也不排除是bug来的。基于你修改了项目代码，问题不好排查。你下载demo。将你的视频替换到demo里面去。如果代理仍然回调nil。那么就可以确定库并不支持这种视频。你可以将视频发给我。迭代版本时会将它兼容的。但是如果demo没有问题，那么可能就是你修改了项目代码的原因，你可以仔细检查一下修改的地方。

**Comment by Miss-Leely** [comment]
再问一个问题哦，就是这个库支持MOV格式的视频吗，因为我对比了一下数据，这个超过10秒的视频是用手机自带的录像机录制的，后缀是MOV格式在LFVideoEdit videoEdit = [[LFVideoEditManager manager] videoEditForAsset:model];取值的时候，videoEdit为nil，MP4格式的是可以获取到值的。

**Comment by lincf0912** [comment]
理论上只要可以转换成AVAsset的视频都支持。

**Comment by lincf0912** [comment]
[版本1.2.6](https://github.com/lincf0912/LFMediaEditingController/releases/tag/1.2.6)
新增可选默认操作类型，希望对你的项目有帮助。

**Comment by Miss-Leely** [comment]
好的，谢谢。
