### ISSUE TITLE
How can we use in Swift?

### ISSUE THREAD

**Issue by VivekGoswami** [lincf0912/LFMediaEditingController#2]
Hi, I have drag class folder in Swift project and trying to use this controller in app but it's not working, so is it possible to used in Swift project?

**Comment by lincf0912** [comment]
Hello, I haven't tried running in the swift project. Let me try it on.

**Comment by lincf0912** [comment]
I tested it. It works in Swift project (pod install &&  drag class folder). But I just tested the picture editor.
The key is to create bridge files (XXX-Bridging-Header.h)
[imagePickerTest_withoutPOD.zip](https://github.com/lincf0912/LFMediaEditingController/files/1310329/imagePickerTest_withoutPOD.zip)
[imagePickerTest.zip](https://github.com/lincf0912/LFMediaEditingController/files/1310330/imagePickerTest.zip)

**Comment by VivekGoswami** [comment]
it will work on video? or just for image?

**Comment by lincf0912** [comment]
both

**Comment by VivekGoswami** [comment]
Thank you so much... for this awesome project :-) @lincf0912

**Comment by Rushang007** [comment]
Hi @lincf0912 
do you add any additional features (like instagram or snapchat) to the current code?

**Comment by lincf0912** [comment]
> Hi @lincf0912 
> 
> do you add any additional features (like instagram or snapchat) to the current code?
> 
> 

There is no update plan for this project.
