### ISSUE TITLE
Main Thread Checker: UI API called on a background thread: -[UIView contentMode]

### ISSUE THREAD

**Issue by fairytale110** [lincf0912/LFMediaEditingController#20]
![image](https://user-images.githubusercontent.com/30248926/55325666-4cc1dd80-54b8-11e9-8aa6-ec3f3e8b93f7.png)

如图所示，编辑图片，点完成，偶尔会出现说在非主线程调用了方法，

**Comment by lincf0912** [comment]
🙏[版本1.3.1](https://github.com/lincf0912/LFMediaEditingController/releases/tag/1.3.1)
