### ISSUE TITLE
裁剪后，对图片进行涂鸦的画笔宽度不正常

### ISSUE THREAD

**Issue by netsesame2** [lincf0912/LFMediaEditingController#21]
对图片裁剪，图片会自动放大到屏幕宽度。这时如果做涂鸦操作，画笔宽度变得比预设的大。

不知道是哪里的代码出现问题，如何修改？谢谢

**Comment by lincf0912** [comment]
请确定你的版本是[1.3.1](https://github.com/lincf0912/LFMediaEditingController/releases/tag/1.3.1)并且未修改过源码。
可以截图看一下吗？

**Comment by netsesame2** [comment]
版本不是最新版，是去年底的版本。对源码做了一些修改

**Comment by lincf0912** [comment]
这个问题版本迭代的时候已经修复了。建议如果需要修改的话最好fork后再改。

**Comment by netsesame2** [comment]
近期的版本改动挺大的，因为我有一些本地化功能定制，所以费了一些功夫才更新上去。

但遇到一个新问题：filter部分，我原来新增了两个自定义滤镜，用的第三方的c代码。
新版本使用LFFilter框架，请假如何才能把自定义的滤镜加进去，而不用破坏现在的框架结构？

**Comment by lincf0912** [comment]
所以说如果你fork了再修改的话。就只需要解决一下冲突就可以了。
你的那个第三方最终是生成一个CIFilter的吗？如果是的话。可以使用LFFilter来初始化它。
如果是直接处理底层数据，类似ColorMatrix的情况。在目前的框架上很难拼接。
你的滤镜是图片还是视频？or both？

**Comment by netsesame2** [comment]
我需要对图片进行二值化处理，涉及两个二值化算法。单凭ColorMatrix无法实现，所以我用了第三方的c库。
之前的版本比较容易接入，改几个case语句。
现在的版本，感觉像个迷宫一样，不知道怎么下手。

**Comment by lincf0912** [comment]
现在的LFFilterSuite框架使用与新增滤镜的门槛低。之前的那种门槛太高了。而且内存使用也高。如果支持gif那就更没法玩了。
你可以新增一个类来继承LFFilter，里面重写父类的方法。同时新增一个显示的类基础LFFilterImageView来实现显示。这样应该是可行的。

**Comment by netsesame2** [comment]
我试试看，非常感谢

**Comment by netsesame2** [comment]
昨天尝试写自己的LFFilter，遇到一个新的问题：
我需要对图片进行像素级的处理，但CIImage 似乎并不支持直接这样做。我尝试转换成UIImage，但是得到的是个大小为0的对象。

希望大神指点一二。

**Comment by lincf0912** [comment]
1. 继承LFFilter
2. 重写父类方法- (CIImage *)imageByProcessingImage:(CIImage *)image atTime:(CFTimeInterval)time;
3. 将原来的滤镜处理方式放到这个方法里面

CIImage转UIImage方法
````
static LFContext *context = nil;
static dispatch_once_t onceToken;
dispatch_once(&onceToken, ^{
    context = [LFContext contextWithType:LFContextTypeDefault options:nil];
});
CGImageRef cgImage = [context.CIContext createCGImage:ciImage fromRect:image.extent];
uiImage = [UIImage imageWithCGImage:cgImage];
````

UIImage转CIImage方法
````
CIImage *ciImage = nil;
if (uiImage != nil) {
    if (uiImage.CIImage != nil) {
        ciImage = uiImage.CIImage;
    } else {
        ciImage = [CIImage imageWithCGImage:uiImage.CGImage];
    }
}
````

**Comment by netsesame2** [comment]
已解决，非常感谢
