### ISSUE TITLE
就是编辑图片的时候，内存太高，很容易崩溃

### ISSUE THREAD

**Issue by caoyunxiao** [lincf0912/LFMediaEditingController#22]

**Comment by lincf0912** [comment]
请问出现在那款机型？系统版本是多少？
模拟器的话，编辑视频或者设计滤镜方面会很高。这是没有适配模拟器的cpu问题。

**Comment by caoyunxiao** [comment]
iPhone XS手机拍的图片，我估计是传入编辑图片太大导致的，一定压缩后，内存情况有好转

**Comment by lincf0912** [comment]
可以参考下LFImagePickerController对LFMediaEditingController的传入图片处理。
或者你尝试使用LFImagePickerController来编辑，看内存是否仍然很高。

**Comment by lincf0912** [comment]
可以更新[版本1.3.2](https://github.com/lincf0912/LFMediaEditingController/releases/tag/1.3.2)试试
