### ISSUE TITLE
LFSplashStateType_Blurry 似乎没有实现

### ISSUE THREAD

**Issue by eric1202** [lincf0912/LFMediaEditingController#23]
首先感谢大哥的开源~

有个疑问, 高斯模糊画笔似乎并没有提供.

请问 LFSplashStateType_Blurry 具体怎么在LFSplashLayer 绘制呢?

**Comment by lincf0912** [comment]
LFSplashStateType_Blurry是有实现的。你需要滑动幅度较大才能显示出来。

它是记录触摸屏幕的坐标并且在坐标上绘制一张“根据背景颜色调整”的图片。
具体的实现可以看LFSplashLayer的源码。


发自我的 iPhone

**Comment by lincf0912** [comment]
不好意思，我记错了。
原来的LFSplashStateType_Blurry实现方式是在加载图片的时创建一个新的高斯模糊图片放在图片展示层的上面。然后通过遮罩的方式，手指触屏坐标区域显示高斯模糊图片的部分来达到效果的。但是加载的时候需要创建多一张高斯模糊图片性能与内存都不好。之前的马赛克也是这样。现在调整了。但LFSplashStateType_Blurry被LFSplashStateType_Paintbrush取代了。但它们明显不属于同一种模糊性质，我仍然保存LFSplashStateType_Blurry，但是它没有实现。
