### ISSUE TITLE
特别长的图分辨丢失

### ISSUE THREAD

**Issue by eric1202** [lincf0912/LFMediaEditingController#24]
感谢老哥开源代码
最近发现了如果传入一个宽高比很长的图会失真 调试了好多地方也未能发现关键代码 
希望老哥能帮助解答一下

![屏幕快照 2019-05-21 上午9 25 26](https://user-images.githubusercontent.com/11612443/58061827-7343f100-7baa-11e9-8499-f071dea6f972.png)
![屏幕快照 2019-05-21 上午9 25 32](https://user-images.githubusercontent.com/11612443/58061829-7343f100-7baa-11e9-9c15-fde2b63091d5.png)
![a01bdea9gy1fxov8sjp3fj20m86bpqv7](https://user-images.githubusercontent.com/11612443/58061830-7343f100-7baa-11e9-8ef6-4aece13f7182.jpg)
图一是预览图
图二是LFPhotoEditingController
图三是测试原图

**Comment by lincf0912** [comment]
图一的预览图是使用 LFImagePickerController 吗？

**Comment by eric1202** [comment]
> 图一的预览图是使用 LFImagePickerController 吗？

不是的 用的其他第三方

**Comment by lincf0912** [comment]
好的。我看看是否兼容问题。感谢你的反馈。

**Comment by eric1202** [comment]
感谢回复

我觉得可能是在GLKView 那边有相关的压缩操作? 不是很懂opengles

**Comment by lincf0912** [comment]
更新[版本1.3.2](https://github.com/lincf0912/LFMediaEditingController/releases/tag/1.3.2)试试
