### ISSUE TITLE
Change navbar button to english?

### ISSUE THREAD

**Issue by dani2906** [lincf0912/LFMediaEditingController#25]
hey, how can I change the navbar left and right buttons to say , Cancel and OK?

**Comment by lincf0912** [comment]
You can copy file(LFMediaEditingController.bundle\LFMediaEditingController.strings) to your project. And modify it. It's a localization file.

发自我的 iPhone

**Comment by dani2906** [comment]
I am really impressed with what you have built. Are you available to do other (paid) freelance projects? Email me at Danny@cardsnacks.com if you are.

**Comment by lincf0912** [comment]
I already emailed you. Look forward to your reply.

发自我的 iPhone
