### ISSUE TITLE
最新版本源码配合HXPhotoPicker使用的时候，选择相机拍摄图片加载缓慢

### ISSUE THREAD

**Issue by lwsitachi** [lincf0912/LFMediaEditingController#28]
https://github.com/SilenceLove/HXPhotoPicker
使用这个图片选择库，在Demo13的时候，使用的是这个图片编辑库，但是该demo中使用的LFMediaEditingController，在图片放大的时候，下方的工具栏容易消失，因此我在demo中更新了最新的LFMediaEditingController源码，但是又发现另一个较严重的问题，就是选择相册中的相机拍摄图片的时候，加载非常缓慢，还会出现马赛克。选择从网上下载的图片就没问题，怀疑是图片大小的原因。

**Comment by lincf0912** [comment]
是的。因为图片超过内置的大小，判定为大图。会分隔成很多张小图来加载的。操作与加载互不影响，没有必要等待加载完毕才开始编辑。它不会使用太多的内存；也不会因为图片太大而崩溃。

**Comment by lwsitachi** [comment]
但是这个效果很差。。。

**Comment by lincf0912** [comment]
这个效果没得选。除非使用另外一些方案。但我暂时找到一个比较好的方案。那些几千*几千的图片正常加载肯定是会崩溃。而且滤镜的效率也会出现卡顿。如果是拍照的图片这个可以稍微调整来兼容它。

**Comment by lwsitachi** [comment]
HXPhotoPicker demo里面的LFMediaEditingController版本是没有这个问题的

**Comment by lincf0912** [comment]
你尝试一下新的版本，修复了误认为拍照的图片为大图的问题。这个判断仍然有些粗暴。后面会再调优的。应该是不会再出现“马赛克”的加载。[1.3.3](https://github.com/lincf0912/LFMediaEditingController/releases/tag/1.3.3)

**Comment by lwsitachi** [comment]
好的谢谢
