### ISSUE TITLE
一点建议

### ISSUE THREAD

**Issue by hbxfnsm** [lincf0912/LFMediaEditingController#30]
既然可以指定初始化操作模式为裁剪。为什么不添加一个初始化裁剪比率的aspectRatio的属性呢？另外建议aspectRatio增加一个圆形
    lfPhotoEditVC.operationType = LFPhotoEditOperationType_crop;
    lfPhotoEditVC.defaultOperationType = LFPhotoEditOperationType_crop;

**Comment by hbxfnsm** [comment]
如果是通过比例裁剪的photoEditData,再次编辑的时候没有还原选择裁剪比率按钮的选中状态和当前比率。导致原来按固定比率裁剪的图片再次进入裁剪的时候，裁剪框可以自由缩放

**Comment by lincf0912** [comment]
朋友，过分了。但我欣赏你。🤓

**Comment by lincf0912** [comment]
[版本1.3.4](https://github.com/lincf0912/LFMediaEditingController/releases/tag/1.3.4)
圆形的剪裁比例虽然是实现了，但是功能上不会展示出来。展示效果与现在的UI格格不入，而且圆形的图片扩展性很差，形态是展示的时候去决定使用哪一种会更好。

**Comment by hbxfnsm** [comment]
秀儿...
毫无疑问这是一个优秀的库.
operationAttrs 这个点子太好了， 要是能再多一些就好了
比如 裁剪能否旋转，能否切换比率，按钮是否隐藏

为作者点赞

**Comment by lincf0912** [comment]
[版本1.3.6](https://github.com/lincf0912/LFMediaEditingController/releases/tag/1.3.6) 
因为你，它又强大了一点点。
