### ISSUE TITLE
1.3.4版本问题

### ISSUE THREAD

**Issue by jiang443** [lincf0912/LFMediaEditingController#31]
加载竖向长图后：
1.图片严重模糊不清
2.添加文字、贴图都会叠加显示在图片中心而不是屏幕中心，此时屏幕上无法看到添加的对象。

**Comment by lincf0912** [comment]
能否提供你的长图资源给我？我使用demo里面的长图（288 × 7960）测试清晰度没有问题。

**Comment by lincf0912** [comment]
更新[版本1.3.5](https://github.com/lincf0912/LFMediaEditingController/releases/tag/1.3.5)
长图的问题我估计是图片尺寸未达到判断的范围内，没有适配长图的展示。

**Comment by jiang443** [comment]
![image](https://user-images.githubusercontent.com/18394413/63347216-4231b300-c389-11e9-9dd1-14f503efbc2f.png)
用这个图片就可以重现问题。
现在我用1.3.3版本一切正常。

**Comment by lincf0912** [comment]
我测试1.3.3与1.3.5的区别，它们呈现的分辨率是一致的。但是它们的显示方式不一样。或许有一部分机型对Metal的渲染问题。
现在[1.3.6](https://github.com/lincf0912/LFMediaEditingController/releases/tag/1.3.6)对显示的问题重新调整，会比1.3.3更清晰。

**Comment by jiang443** [comment]
已测试1.3.6版本，上述问题已不会出现。
另外，在图片放大状态添加的文字与贴图也会是放大状态。此处与之前版本特性不同，不知道是不是有意为之。

**Comment by lincf0912** [comment]
这的确是一个bug. 😩

**Comment by jiang443** [comment]
还有一个问题，提出供参考。
你可以在屏幕画一个圆，总是会有前段部分变成直线。

**Comment by lincf0912** [comment]
绘画开始触发的时候被ScrollView的delay手势拦截了，丢失了一部分滑动的轨迹。👍很细心嘛。
[版本1.3.7](https://github.com/lincf0912/LFMediaEditingController/releases/tag/1.3.7)

**Comment by jiang443** [comment]
已拉取1.3.7，发现以上问题都解决了，谢谢及时更新。
以下是我发现仍存在的问题：
1. 添加文字完成后，点添加的文字进入编辑页。此时编辑页面弹出两个重复的，需要关闭两次。
2. 与之前的版本相比，添加后的默认文字与贴图比较大。（可能不是Bug）

**Comment by lincf0912** [comment]
1、如果是快速点击2次。的确会弹出2次。但是单点不会。
2、文字是根据长度来缩放。它和图片的长度一致的话。大小就是一样的。理论上它们的长度很难一样。

发自我的 iPhone

**Comment by jiang443** [comment]
明白了，谢谢指导
