### ISSUE TITLE
BUG与建议

### ISSUE THREAD

**Issue by hbxfnsm** [lincf0912/LFMediaEditingController#32]
1.demo视频编辑打开直接不停的闪
2.
LFPhotoEditCropCanRotateAttributeName: @(NO),
LFPhotoEditCropCanAspectRatioAttributeName:@(YES)
底部bar布局错乱
3.建议不要让用户纠正图片方向,在框架内部纠正
    if (image.imageOrientation == UIImageOrientationUp) return image;
    
    UIGraphicsBeginImageContextWithOptions(image.size, NO, image.scale);
    [image drawInRect:(CGRect){0, 0, image.size}];
    UIImage *normalizedImage = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();
或者其他更高效的方式。
UIImageWriteToSavedPhotosAlbum(image,nil,nil,nil)我们自己调用相机保存时候图片不管是横屏还是竖屏方向都是正的（作者可以借鉴内部怎么实现）

**Comment by lincf0912** [comment]
最近专注调整图片编辑的问题。忽略了视频编辑的测试。等会更新视频的问题。
现在是兼容图片方向，但是最好是调用者去管理这些问题。（或许有些业务不是使用正方向）
另外UIImageWriteToSavedPhotosAlbum并没有修改图片方向，苹果的所有系统的展示图片的容器调整了相反方向让你看上去是正方向，如果将图片发给window系统就会出现方向不一样的问题。

**Comment by hbxfnsm** [comment]
我查看UIImageWriteToSavedPhotosAlbum横屏拍摄的图片 方向是0...
但是在系统相机直接横屏拍出来的就是3
可能业务还没用到图片方向相关的...那么就用户自己控制图片吧...

**Comment by lincf0912** [comment]
已经是兼容图片方向🧐。
建议上是调用者去控制自己某些需求。过渡依赖框架，不便于以后替换其它框架。

**Comment by hbxfnsm** [comment]
我直接选取相机拍摄的图片编辑一片黑...旋转一下可以显示一半.必须传正方向才可以，纠正方向又会旋转原始图片...所以我目前采取重绘一下图片.但是觉得这种效率不高。作者可以暴露一个是否纠正原图的属性嘛

**Comment by lincf0912** [comment]
是拍摄后直接使用回调的图片来编辑吗？
还是说保存到相册后再调用相册的拍摄图片？

**Comment by hbxfnsm** [comment]
事先直接用手机拍2张图片
一张横（1-1）(<UIImage: 0x280447db0> size {4032, 3024} orientation 0 scale 1.000000)，
一张竖(1-2)（<UIImage: 0x2804410a0> size {3024, 4032} orientation 3 scale 1.000000）
写个demo从系统相机获取/拍摄图片
拍摄的时候保存UIImageWriteToSavedPhotosAlbum到相册
一张横(2-1) (<UIImage: 0x2831ec700> size {4032, 3024} orientation 0 scale 1.000000)
一张竖(2-2)(<UIImage: 0x2831e0070> size {3024, 4032} orientation 3 scale 1.000000)


1-2，2-2编辑直接黑屏，旋转显示一半
2-1，2-1正常
UIImageWriteToSavedPhotosAlbum纠正一下系统没有置方向为0,是我代码处理了方向为0...抱歉.新版本还没有仔细看内部如何处理图片方向的

**Comment by lincf0912** [comment]
很详细🥳；我试着这种情况的兼容问题。

**Comment by lincf0912** [comment]
[版本1.3.8](https://github.com/lincf0912/LFMediaEditingController/releases/tag/1.3.8)
修复了一些bug

**Comment by hbxfnsm** [comment]
你太秀了
