### ISSUE TITLE
视频编辑加文字和贴纸都会导致视频黑屏且只展示文字或者贴纸

### ISSUE THREAD

**Issue by AllLuckly** [lincf0912/LFMediaEditingController#33]
<img width="322" alt="屏幕快照 2019-09-16 上午10 24 19" src="https://user-images.githubusercontent.com/10387295/64931617-2fb57700-d86c-11e9-8ba9-2a00a8d625fc.png">

**Comment by lincf0912** [comment]
请问你使用的库是什么版本的？

**Comment by AllLuckly** [comment]
下载的现在这个包就有这个情况哦 xcode 10.2.1

**Comment by lincf0912** [comment]
你直接下载项目或多或少会有一些问题的。
我推荐你下载框架的方式：
1、使用cocoapod
2、在这里[下载](https://github.com/lincf0912/LFMediaEditingController/releases)

**Comment by AllLuckly** [comment]
好的。
