### ISSUE TITLE
遇到的两个问题

### ISSUE THREAD

**Issue by jiang443** [lincf0912/LFMediaEditingController#34]
目前正在使用Git拉取的最新版本：2019.9.16
遇到以下两个问题：
1. 竖向较长的图片，画曲线或添加文字，生成的editPreviewImage上，曲线、文字明显比较模糊。
可以用这个图片重现：https://user-images.githubusercontent.com/18394413/63347216-4231b300-c389-11e9-9dd1-14f503efbc2f.png
请注意把Demo中PhotoViewController里设置：
imageView.contentMode = UIViewContentModeScaleAspectFill;
否则看不清楚。
https://idt-blood-sugar.oss-cn-shenzhen.aliyuncs.com/bs2/doctor/default/iOS20190917163009PqqEJVA4.png

2. 内存问题。
   因业务需要，我要在一个UITableView里显示与修改多个图片，而每一个图片修改后都会有一个LFPhotoEdit。
在每个图片编辑完成返回后，内存立即增加40M左右。由于图片有多张，最终引起占用内存过
大，APP系统被强制关闭。
以上情况在iphone6/6P及以下手机（内存1G）上可以重现，系统版本iOS11。
因看到LFPhotoEdit的属性成员中有多个UIImage与NSData，会增加不少内存，希望考虑以后可以优化数据结构，减小内存占用。

**Comment by lincf0912** [comment]
当前最新版本是[1.3.8](https://github.com/lincf0912/LFMediaEditingController/releases/tag/1.3.8)
1. 待测试
2. LFPhotoEdit的体积会跟编辑的图片大小成正比。这方面需要调度app去优化自身的内存管理。
我提个建议：
1. 没有重新编辑的需要。不需要持有LFPhotoEdit。仅持有编辑后的图片（editPreviewImage）即可。
2. 有重新编辑的需要。序列化LFPhotoEdit保存到沙盒，不持有LFPhotoEdit，需要编辑的时候反序列化就行。
很遗憾。这个序列化的操作，需要等待下一个版本才能支持。但这只是一个思路。换一个方式。仅保存重要的编辑数据（editImage、editData）。同样可以释放LFPhotoEdit。需要使用的时候再通过保存的编辑数据初始化LFPhotoEdit。

**Comment by jiang443** [comment]
谢谢您的回复，已优化app自身内存管理，图片资源尽量使用沙盒文件缓存。内存问题有一定程序缓解，不过还是占用比较高。
期待您的下一个版本。

**Comment by lincf0912** [comment]
下一个版本的计划比较大。短时间内不会发布的。
我隐约感觉到你的优化并未尽力。
如果你的UITableView不是全屏的话，仅持有editPosterImage就行，它是一张比较小的图片；
UITableView是全屏的。也是仅持有editPreviewImage，它相当于你编辑之前的原图大小（会比原图大一点）。你让editPreviewImage替换了原图，那么你的内存也仅是多了一点。因为editImage是跟你的原图一摸一样的，所以你大可放心释放你的原图，缓存LFPhotoEdit的属性并释放它。这样做我认为不会有太多的内存占用，除非你原图是达到几M的图片。

**Comment by jiang443** [comment]
确实如此。你的思路是很好的，我也有想过实施此方案。最近因项目临近上线，时间紧迫，所以没有做更彻底的优化。目前只是保证了APP不因内存占用过高而被杀死，未来半个月内，我会继续按照此方案做优化。
谢谢您的悉心指教。

**Comment by lincf0912** [comment]
我做了一些测试，它与我所描述的有所不同。
1、即使使用序列化LFPhotoEdit并将其释放，也不见得会节省多少内存。因为序列化的设计是存储一些小数据，序列化本身就会引起很高的内存。
2、调度app释放自身持有的原图来使用LFPhotoEdit的editImage。影响app的实现逻辑与代码可读性。不可取。
我建议你按兵不动。等下一个版本，再测试内存的问题。我会对它做一个全面的内存优化。

**Comment by lincf0912** [comment]
你尝试一下这个版本，它的内存得到了很大的优化 [版本1.3.9](https://github.com/lincf0912/LFMediaEditingController/releases/tag/1.3.9)
