### ISSUE TITLE
非常棒,点赞

### ISSUE THREAD

**Issue by GDGitHubs** [lincf0912/LFMediaEditingController#36]
有一个小小的问题, 添加文字或者涂鸦后,生成的图片有点模糊怎么解决?

**Comment by lincf0912** [comment]
请问你是使用最新[版本1.3.8](https://github.com/lincf0912/LFMediaEditingController/releases/tag/1.3.8)吗？
可以的话，麻烦你提供一下编辑的图片。

**Comment by lincf0912** [comment]
请尝试一下这个[版本1.3.9](https://github.com/lincf0912/LFMediaEditingController/releases/tag/1.3.9)
