### ISSUE TITLE
Pure virtual function called!  虚方法调用？ 

### ISSUE THREAD

**Issue by nico-WX** [lincf0912/LFMediaEditingController#39]
`LFPhotoEditingController *vc = [[LFPhotoEditingController alloc] initWithOrientation:UIInterfaceOrientationPortrait];
        [vc setEditImage:self.coverImage.image];
        [vc setDelegate:self];
        UINavigationController *nav = [[UINavigationController alloc] initWithRootViewController:vc];
        [nav setNavigationBarHidden:YES];
        [self rootVCPresentViewController:nav animated:YES completion:nil];
        `

这段代码显示 控制器 就 报： Pure virtual function called

**Comment by nico-WX** [comment]
另外裁剪较大的图片 裁剪上面部分 ， 得到的是下部分的图片

**Comment by nico-WX** [comment]
好尴尬， 裁剪框裁减掉的是需要的图像，裁剪框内容应该是需要的内容才合理吧

**Comment by nico-WX** [comment]
只裁剪图片的情况下，裁剪的结果是裁剪框外的图像，裁剪完成然后再编辑一下就可以得到需要的内容

**Comment by nico-WX** [comment]
我把代码  改了一下 就能正常了

` // CIImage 的原始坐标在左下角，y值需要重新计算。
    //clipRect.origin.y = (int)((contentSize.height/clipScale - clipRect.size.height - clipRect.origin.y)+0.5)*1.f;`

**Comment by lincf0912** [comment]
你的加载方式比较特别。
1、我使用你的加载方式(我是使用demo修改的。测试的方式我保留了。将PhotoViewController.m 的#define PresentationPageSheet 解除注释)，真机测试没有Pure virtual function called提示。
2、如果你一定要用一个新的导航栏，那么应该是设置这个导航栏的旋转方向，不是使用initWithOrientation。否则横屏的时候会出现问题
3、因使用CIImage的截取方式会出现模糊情况。改为使用CGImage的方法。这行我忘记去掉。很优秀嘛。

**Comment by lincf0912** [comment]
请更新[版本1.4.0](https://github.com/lincf0912/LFMediaEditingController/releases/tag/1.4.0)

**Comment by nico-WX** [comment]
好的，感谢👍👍
