### ISSUE TITLE
图片裁剪:同时drag&clip 点击finish，裁剪结果不对。

### ISSUE THREAD

**Issue by icebluewmm** [lincf0912/LFMediaEditingController#4]
图片裁剪:同时drag&clip 点击finish，裁剪结果不对。

**Comment by lincf0912** [comment]
同时drag&clip 是什么操作？
要么移动、缩放图片，要么移动、缩放剪裁框；
你是说同时移动这2个视图？

**Comment by icebluewmm** [comment]
你尝试 先 拖动 resizecontrol，别松手，同时另一只手再 drag or zoom 图片，点击finish，会发现 croprect 不对。

**Comment by icebluewmm** [comment]
您的这个库十分优秀，况且这种情形确实不常见，但是经过验证，微信确实响应了最终的 gridview 的rect，结果没有问题。
期待你的 fix.

**Comment by lincf0912** [comment]
这个修复优先级很低，先mark。
你有兴趣可以fork来修复；因为finish只对当前视图处理，计算都是在拖动剪裁框与图片的松手后触发的。只需要将松手后的计算放到finish执行一次就可以，如果加上没有松手才计算就更好了。

**Comment by icebluewmm** [comment]
旋转的话也一样会出现这个问题，经常所选区域转着转着就不对了，甚至区域直接出了图外。猜测应该和上一个问题是一个原因，所以您还是抽空修了吧。另外，上一个问题也会导致所选区域出了图外，我也没修好。

**Comment by lincf0912** [comment]
久等了。你提的问题已经修复了。[版本1.1.7](https://github.com/lincf0912/LFMediaEditingController/releases/tag/1.1.7)
1、但我的修复与微信的是有区别的，现在可以同时使用多种手势来编辑，不过并不能finish (因为我的工具栏并不只是cancel&finish, 多出的旋转与固定大小涉及的处理非常大，目前暂时修复到这里了。)
2、如果你仍然需要，可以在LFEditingView的完成编辑时 调用 supplementHandle方法即可，旋转与固定的UI你可以像微信一样移到工具栏外。
