### ISSUE TITLE
这个库很棒

### ISSUE THREAD

**Issue by nevermore0223** [lincf0912/LFMediaEditingController#41]
这个库真的太棒了 只是我发现当图片大于2m的时候再编辑编辑页面图片尺寸会变，而且渲染的时候有可能会出现内存炸掉的情况...不过真的非常感谢楼主 把这么棒的东西分享出来

**Comment by lincf0912** [comment]
方便的话，你给张图片来试试。我测试用10M图片。没有发现问题。

**Comment by lincf0912** [comment]
好的。感谢你的反馈。

发自我的 iPhone

**Comment by lincf0912** [comment]
请更新[版本1.4.1](https://github.com/lincf0912/LFMediaEditingController/releases/tag/1.4.1)

**Comment by nevermore0223** [comment]
🙏🙏🙏感谢楼主大大！------------------ 原始邮件 ------------------
发件人: "Lam"<notifications@github.com>
发送时间: 2020年1月17日(星期五) 下午3:49
收件人: "lincf0912/LFMediaEditingController"<LFMediaEditingController@noreply.github.com>;
抄送: "nevermore0223"<zhz623660515@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [lincf0912/LFMediaEditingController] 这个库很棒 (#41)



请更新版本1.4.1
 
&mdash;
