### ISSUE TITLE
Add Sticker From url

### ISSUE THREAD

**Issue by Aljiachi** [lincf0912/LFMediaEditingController#42]
is there’s any way to add sticker from url?

**Comment by lincf0912** [comment]
For now.  Only local images (png, jpeg, jpg) can be loaded.

**Comment by Aljiachi** [comment]
thanx man for this amazing library hope to add this feature soon.

**Comment by lincf0912** [comment]
Yes. It will. In fact, it's starting.

**Comment by lincf0912** [comment]
Now you can upgrade it. It can already support sticker from URLs.
[version 1.4.2](https://github.com/lincf0912/LFMediaEditingController/releases/tag/1.4.2)
