### ISSUE TITLE
崩溃问题

### ISSUE THREAD

**Issue by yongshideweiyi** [lincf0912/LFMediaEditingController#44]
首先感谢作者提供这么好的编辑库，但是我在使用的时候发现一个必崩的场景
iPhone 5
iOS 10.3.3
编辑图片必崩  1.4.0   1.4.1   1.4.2  三个版本均能复现

**Comment by yongshideweiyi** [comment]
![Uploading 图片.png…]()
会崩溃在这两个地方，崩溃在第一个红色框时会打印

**Comment by yongshideweiyi** [comment]
崩溃在LFBrush+create文件中的

**Comment by yongshideweiyi** [comment]
崩溃在context = [CIContext contextWithOptions:@{kCIContextUseSoftwareRenderer: @(NO)}];和CGImageRef outImage = [context createCGImage:result fromRect:[midImage extent]];两处，偶尔报错xcode libc++abi.dylib: Pure virtual function called!

**Comment by lincf0912** [comment]
更新[版本1.4.3](https://github.com/lincf0912/LFMediaEditingController/releases/tag/1.4.3)

**Comment by nevermore0223** [comment]
大神 最新的版本 编辑视频点击取消基本必崩, 机型是6s ios12.3 1.4.1版本编辑视频没有出现这个问题  崩溃原因:*** -[LFDataFilterVideoView respondsToSelector:]: message sent to deallocated instance 0x10f29bf70

**Comment by lincf0912** [comment]
@nevermore0223 暂时没iOS12的机。这个可能是个例。因为我测试其他系统都是正常。你可以贴出更加详细的崩溃信息吗？

**Comment by nevermore0223** [comment]
...我确实也是只在ios12的6s上出现这个问题，而且是必现,点击完成会报一个   '[avas] AVAudioSession.mm:1079:-[AVAudioSession setActive:withOptions:error:]: Deactivating an audio session that has running I/O. All I/O should be stopped or paused prior to deactivating the audio session.'   然后继续是'-[LFDataFilterVideoView respondsToSelector:]: message sent to deallocated instance 0x10f29bf70' 程序崩掉。抱歉啊老哥，更详细的崩溃信息我也不知道怎么看。我还想问一下 编辑视频或者图片 点击取消dismiss控制器内存涨了7、8M是正常的吗
