### ISSUE TITLE
图片过大，无法发送原图

### ISSUE THREAD

**Issue by SnailLoveSmile** [lincf0912/LFMediaEditingController#46]
图片过大，无法发送原图,  每次点击有会弹出, 下个版本去了吧,  影响不好, 用户不在乎那么多像素的

**Comment by lincf0912** [comment]
1、提示不属于这个框架。而是属于[LFImagePickerController](https://github.com/lincf0912/LFImagePickerController)
2、框架不会对某种业务或喜欢迎合修改。建议Fork后修改。
3、如果你有认真的看过LFImagePickerController.h，你不会提这种issues。
