### ISSUE TITLE
项目中有使用MobileVLCKit出现必崩现象

### ISSUE THREAD

**Issue by nevermore0223** [lincf0912/LFMediaEditingController#48]
![1586851228122](https://user-images.githubusercontent.com/29602022/79200598-44d99f00-7e69-11ea-9b6b-1b24abb2a108.jpg)
![1586851272995](https://user-images.githubusercontent.com/29602022/79200604-460acc00-7e69-11ea-93d8-6af81a803633.jpg)
大神，我的项目里有使用vlc播放rtsp流，在编辑完视频之后dismiss,再进入vlc播放rtsp流,就会必崩，您能否帮我分析一下是什么原因？真的非常感激！

**Comment by lincf0912** [comment]
我没用过VLC。看图应该是重新对VLC播放一个新的流时，旧的流无法释放导致崩溃。可能是旧的视频地址被覆盖了。

**Comment by nevermore0223** [comment]
感谢老哥的回复 &nbsp;我再找找原因 &nbsp;感谢！



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Lam <notifications@github.com&gt;
发送时间: 2020年4月14日 16:36
收件人: lincf0912/LFMediaEditingController <LFMediaEditingController@noreply.github.com&gt;
抄送: nevermore0223 <zhz623660515@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[lincf0912/LFMediaEditingController] 项目中有使用MobileVLCKit出现必崩现象 (#48)





 
我没用过VLC。看图应该是重新对VLC播放一个新的流时，旧的流无法释放导致崩溃。可能是旧的视频地址被覆盖了。

**Comment by nevermore0223** [comment]
正常情况下vlc的使用是ok的，但是一旦打开LFVideoEditingController，无论是编辑视频或者取消退出来，再用vlc播放流就会报上面的错。😂😂
...我都找不到相关文档，老哥 我能➕你qq请教吗？真的很抱歉...

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Lam <notifications@github.com&gt;
发送时间: 2020年4月14日 16:36
收件人: lincf0912/LFMediaEditingController <LFMediaEditingController@noreply.github.com&gt;
抄送: nevermore0223 <zhz623660515@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[lincf0912/LFMediaEditingController] 项目中有使用MobileVLCKit出现必崩现象 (#48)





 
我没用过VLC。看图应该是重新对VLC播放一个新的流时，旧的流无法释放导致崩溃。可能是旧的视频地址被覆盖了。

**Comment by lincf0912** [comment]
你可以做个简单的demo来体现这个问题吗？

**Comment by nevermore0223** [comment]
ok &nbsp;我做完发给您



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Lam <notifications@github.com&gt;
发送时间: 2020年4月14日 17:38
收件人: lincf0912/LFMediaEditingController <LFMediaEditingController@noreply.github.com&gt;
抄送: nevermore0223 <zhz623660515@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[lincf0912/LFMediaEditingController] 项目中有使用MobileVLCKit出现必崩现象 (#48)





 
你可以做个简单的demo来体现这个问题吗？

**Comment by nevermore0223** [comment]
[crashTest.zip](https://github.com/lincf0912/LFMediaEditingController/files/4478886/crashTest.zip)
大神 因为vlc的库太大了 超过1个G..所以我上传不了github podfile里面也没加上，不过我代码都写好了，麻烦您自己用pod下一个...真的不好意思!具体实现步骤就是正常点击播放rtsp的按钮是可以播放流的,但是一旦先打开了LFVideoEditingController开始编辑视频,哪怕点击取消退出来，再次播放rtsp流都会崩溃  拜谢!!!

**Comment by lincf0912** [comment]
这么庞大的库😭。

**Comment by nevermore0223** [comment]
😂😂😂确实挺麻烦的，您那边能复现我说的问题了吗



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Lam <notifications@github.com&gt;
发送时间: 2020年4月16日 16:56
收件人: lincf0912/LFMediaEditingController <LFMediaEditingController@noreply.github.com&gt;
抄送: nevermore0223 <zhz623660515@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[lincf0912/LFMediaEditingController] 项目中有使用MobileVLCKit出现必崩现象 (#48)





 
这么庞大的库😭。

**Comment by lincf0912** [comment]
我恐怕是没有太多时间去处理它。毕竟它实在耗时。但我尽量抽时间吧。
是在podfile 添加 pod 'MobileVLCKit' 吗？

**Comment by nevermore0223** [comment]
嗯嗯 是的😂感谢大神 理解理解



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Lam <notifications@github.com&gt;
发送时间: 2020年4月17日 13:34
收件人: lincf0912/LFMediaEditingController <LFMediaEditingController@noreply.github.com&gt;
抄送: nevermore0223 <zhz623660515@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[lincf0912/LFMediaEditingController] 项目中有使用MobileVLCKit出现必崩现象 (#48)

**Comment by lincf0912** [comment]
因为MobileVLCKit认为[EAGLContext currentContext]都是它创建的。强行release。
`pod update`解决它。

**Comment by nevermore0223** [comment]
感谢大神！我去试试 &nbsp;哈哈 我本来已经放弃vlc了换了个基于ffmpeg实现的库 要是有用我再换回vlc 再次感谢！！！！！！！



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Lam <notifications@github.com&gt;
发送时间: 2020年4月20日 16:41
收件人: lincf0912/LFMediaEditingController <LFMediaEditingController@noreply.github.com&gt;
抄送: nevermore0223 <zhz623660515@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[lincf0912/LFMediaEditingController] 项目中有使用MobileVLCKit出现必崩现象 (#48)





 
因为MobileVLCKit认为[EAGLContext currentContext]都是它创建的。强行release。
 pod update解决它。

**Comment by nevermore0223** [comment]
您是说更新mobileVLC吗 我刚更新了3.3.10的版本vlc这个问题还是没有解决.. 我现在放弃了vlc了，换了个别的方案,感谢大神！！！

**Comment by lincf0912** [comment]
当然是更新LFMediaEditingController了

**Comment by nevermore0223** [comment]
感谢大神!我刚试了下 问题真的解决了！！！太给力啦！！！
