### ISSUE TITLE
文字放大后会产生模糊

### ISSUE THREAD

**Issue by paintingStyle** [lincf0912/LFMediaEditingController#55]
文字放大后会产生模糊，这个能解决下吗

**Comment by lincf0912** [comment]
机型？放大肯定会模糊，但模糊的程度可控。
最好能有个截图。能看看模糊的程度。每个人能接受的程度都不一样。只能大众化定位。

**Comment by paintingStyle** [comment]
模糊要放到最大才有，程度不大，有什么办法可以解决吗

**Comment by lincf0912** [comment]
试试[版本1.4.6](https://github.com/lincf0912/LFMediaEditingController/releases/tag/1.4.6)
