### ISSUE TITLE
设置LFPhotoEditCropExtraAspectRatioAttributeName后如何设置默认裁剪比例

### ISSUE THREAD

**Issue by luzsyn** [lincf0912/LFMediaEditingController#67]
设置LFPhotoEditCropExtraAspectRatioAttributeName:@[
                                             [LFExtraAspectRatio extraAspectRatioWithWidth:9 andHeight:16],
                                             [LFExtraAspectRatio extraAspectRatioWithWidth:364 andHeight:170],
                                     ]后，
如何设置默认裁剪比例呢？LFPhotoEditCropAspectRatioAttributeName好像不生效，defaultAspectRatioIndex好像永远都是Original。
想实现设置默认自定义裁剪比例，比如默认裁剪比例是[LFExtraAspectRatio extraAspectRatioWithWidth:364 andHeight:170]。

![截屏2021-10-15 17 19 30](https://user-images.githubusercontent.com/21351578/137464317-906c8f35-1f6d-4892-8c91-59bb4990cf8f.png)

代码里的 if (index >= 500) 好像永远都不会执行吧？

**Comment by lincf0912** [comment]
是的。它不应该是index，而是subType。
默认自定义比例由LFPhotoEditOperationSubTypeCropAspectRatioOriginal开始。
请更新框架并使用以下初始化代码实现。
LFPhotoEditCropAspectRatioAttributeName:@(LFPhotoEditOperationSubTypeCropAspectRatioOriginal+1), //剪裁尺寸
LFPhotoEditCropExtraAspectRatioAttributeName:@[
                                             [LFExtraAspectRatio extraAspectRatioWithWidth:9 andHeight:16],
                                             [LFExtraAspectRatio extraAspectRatioWithWidth:364 andHeight:170],
                                     ], //自定义纵横比

**Comment by luzsyn** [comment]
Perfect! 
Thank you.
