### ISSUE TITLE
images from the LFMediaEditingController.bundle not loading

### ISSUE THREAD

**Issue by dani2906** [lincf0912/LFMediaEditingController#8]
How to access the images bundle? returns image null for all buttons and stickes
![img_6276](https://user-images.githubusercontent.com/15331605/34438115-4364c504-ec72-11e7-9649-703d999eb4f7.PNG)
![img_5093](https://user-images.githubusercontent.com/15331605/34438116-436e6280-ec72-11e7-836c-cb91a59ef74d.JPG)

**Comment by lincf0912** [comment]
Do you import the LFMediaEditingController with cocoapods？

发自我的 iPhone

**Comment by dani2906** [comment]
Yes.
I got it to work by moving the resource bundle to my local target and not
inside the cocoapod

But curious what was wrong.

**Comment by lincf0912** [comment]
I've tested it. This is my test demo. For reference.


> 在 2017年12月29日，下午10:24，Dimitry Knyajanski <notifications@github.com> 写道：
> 
> Yes.
> I got it to work by moving the resource bundle to my local target and not
> inside the cocoapod
> 
> But curious what was wrong.
>
