### ISSUE TITLE
 editor returns LFVideoEdit nil

### ISSUE THREAD

**Issue by dani2906** [lincf0912/LFMediaEditingController#9]
If not changes were made in the editor and you just tap "OK" the delegate returns LFVideoEdit object as nill

**Comment by lincf0912** [comment]
Yes, LFVideoEdit represents edited data. You can either use it or not.

sample code：
`if (self.videoEdit) {
        lfVideoEditVC.videoEdit = self.videoEdit;
    } else {
        [lfVideoEditVC setVideoURL:self.url placeholderImage:self.firstImage];
    }`
